apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  .Values.minio.name  }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{  .Values.minio.name  }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{  .Values.minio.name  }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name:  {{  .Values.minio.container.name  }}
          image:  {{  .Values.minio.container.image  }}
          resources:
            requests:
              cpu:  {{  .Values.minio.container.resources.requests.cpu  }}
              memory:  {{  .Values.minio.container.resources.requests.memory  }}
            limits:
              cpu:  {{  .Values.minio.container.resources.limits.cpu  }}
              memory:  {{  .Values.minio.container.resources.limits.memory  }}
          command: ['minio', 'server', '/data']
          ports:
             - containerPort: {{ .Values.minio.container.ports.s3  }}
          volumeMounts:
            - mountPath: /data
              name: {{ .Values.minio.name }}
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name  }}
                  key:  AWS_ACCESS_KEY_ID
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name  }}
                  key:  AWS_SECRET_ACCESS_KEY
      volumes:
        - name: {{ .Values.minio.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.minio.name }}
