{{- if .Values.historian.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alfalfa.fullname" . }}-influxdb
  labels:
    {{- include "alfalfa.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ include "alfalfa.influxdb.username" . }}
  password: {{ include "alfalfa.influxdb.password" . }}
{{ end }}