apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.worker.name  }}
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.worker.name  }}
      release: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ .Values.worker.name  }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
        - name: init-wait-for-db
          image: alpine
          command: ["/bin/sh", "-c", "for i in $(seq 1 300); do nc -zvw1 {{  .Values.mongo.name  }} {{ .Values.mongo.container.ports.db_port }} && exit 0 || sleep 3; done; exit 1"]
        - name: init-wait-for-minio
          image: alpine
          command: ["/bin/sh", "-c", "for i in $(seq 1 300); do nc -zvw1 {{  .Values.minio.name  }} {{ .Values.minio.container.ports.web  }} && exit 0 || sleep 3; done; exit 1"]
      containers:
        - name:  {{ .Values.worker.container.name  }}
          image: {{ .Values.worker.container.image  }}
          resources:
            requests:
              cpu:  {{  .Values.worker.container.resources.requests.cpu  }}
              memory:  {{  .Values.worker.container.resources.requests.memory  }}
            limits:
              cpu:  {{  .Values.worker.container.resources.limits.cpu  }}
              memory:  {{  .Values.worker.container.resources.limits.memory  }}
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name  }}
                  key:  AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name  }}
                  key:  AWS_SECRET_ACCESS_KEY
            - name: INFLUXDB_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name  }}
                  key:  INFLUXDB_ADMIN_USER
            - name: INFLUXDB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name  }}
                  key:  INFLUXDB_ADMIN_PASSWORD
            - name: NODE_ENV
              value: {{ .Values.env.public.NODE_ENV }}
            - name: JOB_QUEUE
              value: {{ .Values.env.public.JOB_QUEUE }}
            - name: MONGO_URL
              value: {{ .Values.env.public.MONGO_URL }}
            - name: MONGO_DB_NAME
              value: {{ .Values.env.public.MONGO_DB_NAME }}
            - name: LOGLEVEL
              value: {{ .Values.env.public.LOGLEVEL }}
            - name: S3_URL
              value: {{ .Values.env.public.S3_URL }}
            - name: REDIS_HOST
              value: {{ .Values.env.public.REDIS_HOST }}
            - name: S3_BUCKET
              value: {{ .Values.env.public.S3_BUCKET }}
            - name: REGION
              value: {{ .Values.env.public.REGION }}
            - name: DASHBOARD_URL
              value: {{ .Values.env.public.DASHBOARD_URL }}
            - name: INFLUXDB_DB
              value: {{ .Values.env.public.INFLUXDB_DB }}
            - name: INFLUXDB_HOST
              value: {{ .Values.env.public.INFLUXDB_HOST }}
            - name: HISTORIAN_ENABLE
              value: {{ .Values.env.public.HISTORIAN_ENABLE | quote }}
