apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongo.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mongo.name  }}
      release: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ .Values.mongo.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.mongo.container.name }}
          image: {{ .Values.mongo.container.image }}
          resources:
            requests:
              cpu:  {{  .Values.mongo.container.resources.requests.cpu  }}
              memory:  {{  .Values.mongo.container.resources.requests.memory  }}
            limits:
              cpu:  {{  .Values.mongo.container.resources.limits.cpu  }}
              memory:  {{  .Values.mongo.container.resources.limits.memory  }}
          ports:
            - containerPort:  {{ .Values.mongo.container.ports.db_port }}
          volumeMounts:
            - mountPath: /data/db
              name: {{ .Values.mongo.name }}
      volumes:
        - name: {{ .Values.mongo.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.mongo.name }}

