apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.name   }}
spec:
  selector:
    app: {{ .Values.web.name  }}
    release: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.web.container.ports.http  }}
    - name: test
      protocol: TCP
      port:  {{ .Values.web.container.ports.test }}
