{{- if and .Values.mongodb.enabled .Values.mongodb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "alfalfa.fullname" . }}-mongodb-pvc
  labels:
    {{- include "alfalfa.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.mongodb.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size | quote }}
  {{- if .Values.mongodb.persistence.storageClass }}
  {{- if (eq "-" .Values.mongodb.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.mongodb.persistence.storageClass }}"
  {{- end }}
  {{- end }}
{{- end }}
