name: Release Helm Charts

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.14.0'

      - name: Add Helm repositories
        run: |
          helm repo add elastic https://helm.elastic.co
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update

      - name: Package Alfalfa Chart
        run: |
          cd alfalfa-chart
          helm dependency build
          cd ..
          helm package alfalfa --destination ./packages

      - name: Upload Chart Packages to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            packages/*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Charts to OCI Registry
        run: |
          for chart in packages/*.tgz; do
            chart_name=$(basename "$chart" .tgz)
            helm push "$chart" oci://ghcr.io/${{ github.repository_owner }}/helm-charts
          done

      - name: Generate Chart Index
        run: |
          mkdir -p gh-pages
          helm repo index packages --url https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }} --merge gh-pages/index.yaml || true
          mv packages/index.yaml gh-pages/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
          keep_files: true
